#!/bin/sh -e
#
# - apt search 🤝 fzf

apt-cache search "${@:-.}" | # Use apt-cache for it's 1 line per entry formatting.
	fzf --multi --preview='apt show {1}' | awk '{print $1}' | tr '\n' ' ' |
	clipe
