#!/bin/sh -e
#
# - single command routine updates for apt distros
#
# https://github.com/docwhat/dotfiles/blob/main/bin/apt-upgrade

non_destructive()
(
	set -x
	sudo apt update
	apt list --upgradable
)

destructive()
(
	set -x
	sudo apt upgrade -y
	sudo apt autoremove -y
)

main()
{
	non_destructive

	printf %s\\n 'aptgrade: upgrade and autoremove? C-c to cancel or C-d to continue.'
	cat >/dev/null

	destructive
}

type apt >/dev/null 2>&1 || exit 1

"${1:-main}"
