#!/bin/sh -e
#
# - bluetoothctl buddy

disconnects()
{
	bluetoothctl devices Connected | while read -r _ mac name; do
		printf %s\\n "bluetoothctl disconnect ${mac} # ${name}"
	done
}

connects()
{
	bluetoothctl devices Paired | while read -r _ mac name; do
		printf %s\\n "bluetoothctl connect ${mac} # ${name}"
	done
}

main()
{
	# We filter empty lines because $(connects) or $(disconnects) may be
	# empty lines.
	cat<<-EOF | sed '/^$/d'| fzf --nth=2.. | sh
		$(connects)
		$(disconnects)
		bluetoothctl power off
		bluetoothctl power on
		# exit
	EOF
}

"${@:-main}"
