#!/bin/sh -e
#
# - optimistically tee to clipboard
#
# Will copy stdin if there is any.
# Prints contents by default, so you can use it like tee.
#
# $stream | cbx
# cbx | $filter
#
# TODO: make work on no-clipboard environments.

case "$(uname -s)" in
	# TODO: FreeBSD, NetBSD, OpenBSD, Windows (Windows_NT).
	('Darwin')
		if command -v 'pbcopy' >/dev/null 2>&1; then
			cbxi='pbcopy'
		fi
		# if command -v 'pbpaste' >/dev/null 2>&1; then
		# 	cbxo='pbpaste'
		# fi
		;;
	('Linux')
		if command -v 'xsel' >/dev/null 2>&1; then
			cbxi='xsel -bi'
			# cbxo='xsel -bo'
		elif command -v 'xclip' >/dev/null 2>&1; then
			cbxi='xclip -i -selection clipboard'
			# cbxo='xclip -o -selection clipboard'
		fi
		;;
	(*)
		printf %s\\n "OS not supported, just piping to stdin:"
		;;
esac

stdin="$(cat -)
"

if test -n "$cbxi"; then
	printf %s "$stdin" | $cbxi
fi
printf %s "$stdin"
