#!/bin/sh -e
#
# - optimistically tee to clipboard
#
# Will copy stdin if there is any.
# Prints contents by default, so you can use it like tee.
#
# $stream | clipe
# clipe | $filter
#
# TODO: make work on no-clipboard environments.

case "$(uname -s)" in
	# TODO: FreeBSD, NetBSD, OpenBSD, Windows (Windows_NT).
	('Darwin')
		if command -v 'pbcopy' >/dev/null 2>&1; then
			clipe_prg='pbcopy'
		fi
		;;
	('Linux')
		if command -v 'xsel' >/dev/null 2>&1; then
			clipe_prg='xsel -bi'
		elif command -v 'xclip' >/dev/null 2>&1; then
			clipe_prg='xclip -i -selection clipboard'
		fi
		;;
	(*)
		printf %s\\n "error: OS not supported, just piping to stdin:" 1>&2
		;;
esac

stdin="$(cat -)"

if test -n "$clipe_prg"; then
	printf %s "$stdin" | $clipe_prg
fi
printf %s\\n "$stdin"
