#!/bin/sh -e
#
# - curl with generated directory path
#
# usage: curlx "$link" "$opts"

type curl >/dev/null 2>&1 || exit 1

cd "${HOME}/dl"

url="$1"
shift

case "$url" in
	(*'://'*)  dest="${url#*://}"  ;; # Strip protocol if there is one.
	(*)        dest="$url"         ;;
esac

curl --create-dirs -o "$dest" ${1+"$@"} -- "$url"
