#!/bin/sh -e
#
# - curl with generated directory path
#
# usage: curlx "$link" "$opts"

url="$1"
shift

case "$url" in
	(*'://'*)  dest="${url#*://}"  ;; # Strip protocol if there is one.
	(*)        dest="$url"         ;;
esac

# dest="$(printf %s "$url" | sed 's|/|%/g')"

curl --create-dirs -o "$dest" ${1+"$@"} -- "$url"


