#!/bin/sh -e
#
# - docker ID picker

fo='--header-lines=1 --multi'

sel() {
	tr '\n' ' ' | tee /dev/tty | xsel -ib
	printf \\n 1>&2
}

case "$1" in
	# shellcheck disable=2086 # Intentional: "Double quote to prevent globbing and word splitting."
	(c)   docker container ls     | fzf $fo --preview="docker logs     {1}" | awk '{print $1}' | sel ;;
	(ca)  docker container ls -a  | fzf $fo --preview="docker logs     {1}" | awk '{print $1}' | sel ;;
	(i)   docker image ls         | fzf $fo --preview="docker inspect  {3}" | awk '{print $3}' | sel ;;
	(ia)  docker image ls -a      | fzf $fo --preview="docker inspect  {3}" | awk '{print $3}' | sel ;;
	(n)   docker network ls       | fzf $fo --preview="docker inspect  {1}" | awk '{print $1}' | sel ;;
	(v)   docker volume ls        | fzf $fo --preview="docker inspect  {2}" | awk '{print $2}' | sel ;;
	(*)   exit 1 ;;
esac
