#!/bin/sh -e
#
# - docker ID picker

mode_pick()
{
	fzf -n1 --header-lines=1<<-EOF | awk '{ print $1 }'
		Choose mode:
		c   container
		ca  container --all
		i   image
		ia  image --all
		n   network
		v   volume
	EOF
}
mode="${1:-$(mode_pick)}"

f()
{
	fzf -m --bind ctrl-a:select-all --header-lines=1 --preview-window=bottom --preview="$2" |
		awk "{ print \$$1 }" |
		tr '\n' ' ' |
		cbx
}

case "$mode" in
	(c)   docker container ls     | f 1 'docker logs {1}' ;;
	(ca)  docker container ls -a  | f 1 'docker logs {1}' ;;
	(i)   docker image ls         | f 3 'docker inspect {3}' ;;
	(ia)  docker image ls -a      | f 3 'docker inspect {3}' ;;
	(n)   docker network ls       | f 1 'docker inspect {1}' ;;
	(v)   docker volume ls        | f 2 'docker inspect {2}' ;;
	(*)   exit 1 ;;
esac
