#!/usr/bin/env bash
#
# - WIP uri-escape text
#
# TODO: stdin?
#
# https://www.werockyourweb.com/url-escape-characters/
# https://github.com/dylanaraps/pure-bash-bible#percent-encode-a-string
#
# TODO: what is the correct minimum ammount of characters to escape?

urlencode() {
	# Usage: urlencode "string"
	local LC_ALL=C
	for (( i = 0; i < ${#1}; i++ )); do
		: "${1:i:1}"
		case "$_" in
			[a-zA-Z0-9.~_-])
				printf '%s' "$_"
				;;
			*)
				printf '%%%02X' "'$_"
				;;
		esac
	done
	printf '\n'
}
# urldecode() {
# 	# Usage: urldecode "string"
# 	: "${1//+/ }"
# 	printf '%b\n' "${_//%/\\x}"
# }

urlencode "$1"
