#!/usr/bin/env bash
#
# - dmenu_run but with fmenu
#
#!/bin/sh -e # TODO.

set -eu -o pipefail

{
	printf %s\\n 'Pick a command (or press "!" to run your query):'
	compgen -c | LC_ALL=C sort -u
} |
	fmenu --bind '!:print-query' --header-lines=1 --header-first ${1+"$@"} |
	${SHELL:-"bin/sh"}
