#!/bin/sh -e
#
# - GitHub gist helper
#
# TODO: take extension from $1

type gh >/dev/null 2>&1 || exit 1

magic_id='NEW'

pick_id() {
	{
		printf %s\\n "$magic_id"
		gh gist list -L 999 2>/dev/null |
			sed 's/\t\t/\t-\t/g' | # Empty field -> '-'.
			column -t -s"	" |
			sort -k 2
	} | fzf -n2.. --preview='gh gist view {1} 2>/dev/null' \
		--preview-window=bottom | awk '{ print $1; }'
}

# If passed stdin, always create a new gist:
if test -p /dev/stdin; then
	cat - "${@:-/dev/null}" | vipe ${GIST_SUFFIX+"--suffix ${GIST_SUFFIX}"} |
		gh gist create - -w | awk '{ print $2 }' | clipe
	exit $?
fi

id="$(pick_id)"
if test "$id" = "$magic_id"; then
	cat "${@:-/dev/null}" | vipe ${GIST_SUFFIX+"--suffix ${GIST_SUFFIX}"} |
		gh gist create - -w | awk '{ print $2 }' | clipe
else
	gh gist edit "$id"
fi
