#!/bin/sh -e
#
# - GitHub gist helper
#
# TODO: take extension from $1

magic_id='NEW'

pick_id() {
	{
		printf %s\\n "$magic_id"
		gh gist list 2>/dev/null |
			sed 's/\t\t/\t-\t/g' | # Empty field -> '-'.
			sed 's/\t/  /g' |
			es
	} |
		fzf -n2.. --preview='gh gist view {1} 2>/dev/null' |
		awk '{ print $1; }'
}

# If passed stdin, always create a new gist:
if test -p /dev/stdin; then
	cat - "${@:-/dev/null}" |
		vipe ${GIST_SUFFIX+"--suffix ${GIST_SUFFIX}"} |
		gh gist create - -w |
		awk '{ print $2 }' |
		cbx
	exit $?
fi

id="$(pick_id)"
if test "$id" = "$magic_id"; then
	cat "${@:-/dev/null}" |
		vipe ${GIST_SUFFIX+"--suffix ${GIST_SUFFIX}"} |
		gh gist create - -w |
		awk '{ print $2 }' |
		cbx
else
	gh gist edit "$id"
fi
