#!/bin/sh -e
#
# - GitHub gist helper
#
# TODO: take extension from $1

dir="$(mktemp -d ${TMPDIR:-"/tmp"}/gist.XXX)"
file="${dir}/gistfile1${GIST_SUFFIX+."${GIST_SUFFIX}"}"
cleanup() {
	rm "$dir" -r
}
trap cleanup EXIT

cat ${@:-/dev/null} |
	vipe --suffix "${GIST_SUFFIX}" |
	tee >"${file}"

gh gist create "${file}" |
	tee /dev/tty |
	xargs xdg-open
