#!/bin/sh -e
#
# - git ref picker
#
# git revert $(git shax)

type git >/dev/null 2>&1 || exit 1
type fzf >/dev/null 2>&1 || exit 1

preview=''
if test "$(tput cols)" -ge '138'; then # 138 = 8 SHA + 50 message + 80 preview.
	preview='git show {1}'
fi

git log --abbrev-commit --color=always --decorate=full --pretty=oneline |
	fzf --ansi --multi --preview="$preview" |
	awk '{print $1}' |
	tr '\n' ' ' |
	clipe
