#!/bin/sh -e
#
# - git clonex redo
#
# git clonet $mode $url
#
# git clonet https://r.e/p/o == git clone https://a.b/c/d https+++a.b+c+d

command -v git >/dev/null 2>&1 || exit 1

url="$1"; shift

# Replace illegal characters with '+':
dir="$(printf %s\\n "$url" | tr ':/@' '+++')"

# Test git-clonext in ~/src/+/. for now:
# dir="${HOME}/src/+/${dir}"

git clone ${1+"$@"} "$url" "$dir"
echo "${dir}" | clipe
