#!/bin/sh -e
#
# - git-clonex for submodules
#
# No a/r option, only relative paths allowed.

type git >/dev/null 2>&1 || exit 1

url="$1"
shift

case "$url" in
	(*'://'*)  dir="${url#*://}"  ;; # Strip protocol if there is one.
	(*)        dir="$url"         ;; # Case for user@host type URLs.
esac

(
	set -x
	echo "${dir}" | clipe
	git submodule add ${1+"$@"} "$url" "$dir"
)
