#!/bin/sh -e
#
# - organize your git clones
#
# git clonex $mode $url
#
# git clonex a https://r.e/p/o == git clone https://a.b/c/d ~/src/r.e/p/o
# git clonex r https://r.e/p/o == git clone https://a.b/c/d ./r.e/p/o
#
# TODO: clarify whether clone root is ./ or ./src

mode="$1"
url="$2"
shift
shift

case "$url" in
	(*'://'*) # Strip protocol if there is one.
		dir="${url#*://}"
		;;
	(*)
		# Case for user@host type URLs.
		# TODO: do something else for user@host type urls.
		dir="$url"
		;;
esac

case "$mode" in
	(a) dir="${HOME:-'~'}/src/${dir}"  ;; # "absolute"
	(r) dir="./${dir}"                 ;; # "relative"
	(*) exit 1                         ;;
esac

(
	set -x
	echo "${dir}" | cbx
	git clone ${1+"$@"} "$url" "$dir"
)
