#!/usr/bin/env bash
#
# - organize your git clones
#
# git clonex $clonex_opts $url $clone_opts
#
# git clonex     git:r.e:p/o.git == git clone git:r.e:p/o.git ~/src/r.e/p/o.git
# git clonex     https://r.e/p/o == git clone https://a.b/c/d ~/src/r.e/p/o
# git clonex -r  https://r.e/p/o == git clone https://a.b/c/d ./r.e/p/o
#
# TODO: add --go mode.
# TODO: remove bashisms and use sh.
# TODO: try to convert https to ssh clones.

set -eu -o pipefail

type git >/dev/null 2>&1 || exit 1

strip_protocol() {
	case "$1" in
		(*'://'*)
			printf %s "${1##*://}"
			;;
		(*'@'*)
			dir="${1}"
			dir="${dir##*@}"
			dir="${dir/:/\/}" # FIXME: bashism.
			printf %s "${1}"
			;;
		(*)
			printf %s "${1/:/\/}" # FIXME: bashism.
			;;
	esac
}

mode_root() {
	case "$1" in
		('--absolute')  printf %s "${HOME}/src" ;;
		('--relative')  printf %s "./" ;;
		('--tmp')       printf %s "/tmp/${USER}" ;;
		(*) exit 1 ;;
	esac
}

mode='--absolute' # Default mode.
case "$1" in
	('--relative'|'-r')
		mode='--relative'
		shift
		;;
	('--tmp')
		mode='--tmp'
		shift
		;;
	(*)
		;;
esac

url="$1"; shift
dir="$(strip_protocol "${url}")"
prefix="$(mode_root "$mode")"
dest="${prefix}/${dir}"

(
	# TODO: clone to a tmp repo.
	set -x
	git clone ${1+"$@"} --depth 1 --recursive "$url" "$dest"
)

tput setaf 2
printf %s\\n "cd ${dest}"
tput sgr0
