#!/bin/sh -e
#
# - organize your git clones
#
# git clonex $mode $url
#
# git clonex a https://r.e/p/o == git clone https://a.b/c/d ~/src/r.e/p/o
# git clonex r https://r.e/p/o == git clone https://a.b/c/d ./r.e/p/o
#
# TODO: clarify whether clone root is ./ or ./src

mode="$1"
url="$2"
shift
shift

case "$url" in
	(*'://'*)  dir="${url#*://}"  ;; # Strip protocol if there is one.
	(*)        dir="$url"         ;; # Case for user@host type URLs.
esac

case "$mode" in
	(a) dir="${HOME:-'~'}/src/${dir}"  ;; # "absolute"
	(r) dir="./${dir}"                 ;; # "relative"
	(*) exit 1                         ;;
esac

(
	set  -x
	git clone "$url" "$dir" ${1+"$@"}
	echo ${dir} | xsel -ib
)
