#!/bin/sh -e
#
# - git commit ID picker
#
# git revert $(git shax)

preview=''
if test "$(tput cols)" -ge '138'; then # 138 = 8 SHA + 50 message + 80 preview.
	preview='git show {1}'
fi

git log --oneline |
	fzf --preview="$preview" |
	awk '{print $1}' |
	tee /dev/tty |
	cbx
