#!/bin/sh -e
#
# - get url from git-clonet generated dir

dir="$1"
if test -z "$dir"; then
	dir="${PWD##*/}"
fi

if printf %s\\n "$dir" | grep -F '+++' >/dev/null; then
	printf %s\\n "$dir" |
		sed 's|+|:|; s|+|/|g'
else
	printf %s\\n "$dir" |
		sed 's|+|@|; s|+|:|; s|+|/|g'
fi
