#!/bin/sh -eu
#
# - https://blog.fredrb.com/2023/08/13/bash-one-liner-gomod/

<./go.mod \
	grep '	github.com/' |
	sed 's/\t//' | sed 's/\ v.*//' |
	sed 's|github\.com/\([^/]*\/[^/]*\).*|\1|p' |
	uniq |
	while read -r repo; do
		last_commit="$(gh api "/repos/$repo/commits" | jq -r '.[0].commit.author.date' | sed 's/\(.*\)T.*/\1/')"
		stargazers="$(gh api "/repos/$repo" -q '.stargazers_count')"
		url="github.com/$repo"
		printf "Last commit: %10s | %5s ⭐ | %s\n" "$last_commit" "$stargazers" "$url"
	done
