#!/bin/sh
#
# - even lighter weight ix.io client

type curl >/dev/null 2>&1 || exit 1
type vipe >/dev/null 2>&1 || exit 1

cat "${@:-/dev/null}" | vipe | curl -F 'f:1=<-' ix.io | clipe |
	xargs "${BROWSER:-firefox}"
