#!/bin/sh -e
#
# - concatenate mp3s
#
# https://bytefreaks.net/applications/how-we-concatenate-multiple-mp3-files-into-one-using-ffmpeg

if test "$#" -le '2'; then
	printf 'not enough arguments\n' 1>&2
	exit 1
fi

f="${TMPDIR:-/tmp}/catmp3.$(seed).mp3"
on_exit() {
	rm "$f"
}
trap on_exit EXIT

url="concat:${1}"
shift
for i in "$@"; do
	url="${url}|${i}"
done

ffmpeg -i "$i" -acodec copy "$f"
cat "$f"
