#!/bin/sh -e
#
# - concatenate mp3s
#
# https://bytefreaks.net/applications/how-we-concatenate-multiple-mp3-files-into-one-using-ffmpeg

test "$#" -le '2' && {
	printf 'not enough arguments\n' 1>&2
	exit 64
}

f="${TMPDIR:-/tmp}/catmp3.$(seed).mp3"
cleanup() {
	rm "$f"
}
trap cleanup EXIT

url="concat:${1}"
shift
for i in "$@"
do
	url="${url}|${i}"
done

ffmpeg -i "$i" -acodec copy "$f"
cat "$f"
