#!/bin/sh -e
#
# - ydr everything in this folder

d="${1:-${HOME}/Music}"
cd "$d" || exit 1

maybe_render_tsv()
{
	# TODO: test.
	if test -t 1 && command -v sponge >/dev/null 2>&1; then
		sponge | column -t -s'	' -- -
	else
		cat -
	fi
}

find . -path '*.mp3' |
	ydr
