#!/bin/sh -e
#
# - poor man's notify-send

if test "$#" -eq '0'; then
	s="$(cat -)"
else
	s="$*"
fi

cmd="echo"
if type figlet >/dev/null 2>&1; then
	cmd="figlet"
fi
if type cowsay >/dev/null 2>&1; then
	cmd="cowsay"
fi

xterm -e "tput bel; $cmd '$s'; read -r x"
