#!/bin/sh -e
#
# - shellcheck for piping selections through
#
# $ echo 'echo $double_quote' | sheck
# echo "$double_quote"

date="$(date -u +'%Y%m%d%H%M%S')"
dir="${TMPDIR:-/tmp}/sheck-${date}-$(seed)"
on_exit() {
	rm -rf "$dir"
}
trap on_exit EXIT
cd "$dir" || exit 1

cat - >file
shellcheck -f diff file 2>/dev/null | patch -p1 >/dev/null
cat file
