#!/bin/sh -e
#
# - cgpt to exec

system_prompt="
Write a single line of bash code for the given task, that the user should be able to copy, paste, and execute, as is.
"

cat - | cgpt "$system_prompt" | clipe
