#!/bin/sh -e
#
# - run script in current terminal or spawn one
#
# TODO: support multiple terminals.
#	You'd think checking whether options are available until you find one
#	would do the trick, but all terminals don't have the same flags
# TODO: checking $TERM works, but I'm not sure if it's correct.

command -v xterm >/dev/null 2>&1 || exit 1

if test -z "$TERM" -o "$TERM" = 'dumb'; then
	xterm -e "$@"
else
	sh -c "$@"
fi
