#!/bin/sh -e
#
# - toggle light and dark versions of Yaru gtk-theme
#
# TODO turn into general purpose theme switcher
#	how to know what theme to use? how does neofetch do it?
#
# TODO: s/dconf/gsettings/ ?

case "$(gsettings get org.gnome.desktop.interface color-scheme)" in
	"'prefer-dark'")
		gsettings set org.gnome.desktop.interface color-scheme prefer-light
		;;
	"'prefer-light'")
		gsettings set org.gnome.desktop.interface color-scheme prefer-dark
		;;
	*)
		# echo "$current_theme"
		exit 1
		;;
esac

