#!/bin/sh -eux
#
# - toggle light and dark theme

isLight() {
	if type gsettings >/dev/null 2>&1; then # GNOME
		case "$(gsettings get org.gnome.desktop.interface color-scheme)" in
			("'prefer-dark'") return 1 ;;
			("'prefer-light'") return 0 ;;
		esac
	fi
	if type xfconf-query >/dev/null 2>&1; then # XFCE
		case "$(xfconf-query -c xsettings -p /Net/ThemeName)" in
			('Adwaita-dark') return 1 ;;
			('Adwaita') return 0 ;;
		esac
	fi
}

if isLight; then
	gsettings set org.gnome.desktop.interface color-scheme prefer-dark || true # GNOME
	xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark" || true # XFCE
else
	gsettings set org.gnome.desktop.interface color-scheme prefer-light || true # GNOME
	xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita" || true # XFCE
fi
