#!/bin/sh -e
#
# - use the right vi

type nvim     >/dev/null 2>&1 && exec nvim ${1+"$@"}
type vim      >/dev/null 2>&1 && exec vim ${1+"$@"}
type nvi      >/dev/null 2>&1 && exec nvi ${1+"$@"}
type busybox  >/dev/null 2>&1 && exec busybox vi ${1+"$@"}
