#!/bin/sh -e
#
# - use the right vi

command -v nvim     >/dev/null 2>&1 && exec nvim ${1+"$@"}
command -v vim      >/dev/null 2>&1 && exec vim ${1+"$@"}
command -v nvi      >/dev/null 2>&1 && exec nvi ${1+"$@"}
command -v busybox  >/dev/null 2>&1 && exec busybox vi ${1+"$@"}
