#!/bin/sh -e
#
# - edit clipboard contents (as if) in place
#
# idea: write to clipboard on every write to the tmp file?

termx "xsel -ob | vipe | tee $(mktemp ${TMPDIR:-'/tmp'}/viclip-bak-$(datestamp).XXX) | xsel -ib"
