#!/bin/sh -e
#
# - vim anywhere!* edit clipboard contents (as if) in place
# *or whatever your $EDITOR is
#
# idea: write to clipboard on every write to the tmp file?
# BUG: sometimes randomly fails.

termx "xsel -ob | vipe | tee $(mktemp "${TMPDIR:-'/tmp'}"/viclip-bak-$(datex sort).XXX) | xsel -ib"
