#!/bin/sh -e
#
# - modified version of vim's less.sh script
#
# /usr/share/vim/vim82/macros/less.sh

if test -t 1; then
	vi -c 'set nomodifiable readonly' "${@:--}" # 'vi' might be vim or nvim.
else
	cat "${@:--}"
fi

# #!/bin/sh
# # Shell script to start Vim with less.vim.
# # Read stdin if no arguments were given and stdin was redirected.
#
# if test -t 1; then
#   if test $# = 0; then
#     if test -t 0; then
#       echo "Missing filename" 1>&2
#       exit
#     fi
#     vim --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' -
#   else
#     vim --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' "$@"
#   fi
# else
#   # Output is not a terminal, cat arguments or stdin
#   if test $# = 0; then
#     if test -t 0; then
#       echo "Missing filename" 1>&2
#       exit
#     fi
#     cat
#   else
#     cat "$@"
#   fi
# fi
