#!/bin/sh -e
#
# - modified version of vim's less.sh script
#
# Copied from /usr/share/vim/vim81/macros/less.sh

if test -t 1; then
  if test $# = 0; then
    if test -t 0; then
      echo "Missing filename" 1>&2
      exit
    fi
    vim -c 'set nomodifiable readonly' -
  else
    vim -c 'set nomodifiable readonly' -p "$@"
  fi
else
  # Output is not a terminal, cat arguments or stdin
  if test $# = 0; then
    if test -t 0; then
      echo "Missing filename" 1>&2
      exit
    fi
    cat
  else
    cat "$@"
  fi
fi
