#!/bin/sh -eu
#
# - set volume

cat_opts() {
	cat<<-EOF | sed '/^$/d'
		amixer sset 'Master' 00%
		amixer sset 'Master' 10%
		amixer sset 'Master' 20%
		amixer sset 'Master' 30%
		amixer sset 'Master' 40%
		amixer sset 'Master' 50%
		amixer sset 'Master' 60%
		amixer sset 'Master' 70%
		amixer sset 'Master' 80%
		amixer sset 'Master' 90%
		amixer sset 'Master' 100%
	EOF
}

choose() {
	cat_opts | fzf \
		--nth=2.. \
		--header="Choose an action or press ctrl-c to cancel:" \
		--header-first \
		--
}

run_choice() {
	choose | sh -x
}

main() {
	# FIXME: work without recursion.
	termx "$0 run_choice" || exit 0
}

"${@:-main}"
