#!/bin/sh -e
#
# - archive a webpage with wget
#
# https://dheinemann.com/posts/2022-02-05-archiving-a-website-with-wget
# https://www.petekeen.net/archiving-websites-with-wget
# https://gist.github.com/mullnerz/9fff80593d6b442d5c1b

ua="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)"

cd "${HOME}/dl" || exit 1
wget -mckpE -e robots=off --user-agent="$ua" -- "$@"
