#!/bin/sh -e
#
# - comfy yt-dlp (youtube-dl++) wrapper
#
#	yd clean|md3|mp3p|vid|vidp

yd() {
	printf %s\\n 'Enter links one by line, press ctrl-D when done or ctrl-C to cancel:'
	spongex | xargs -r yt-dlp ${1+"$@"}
}

case "$1" in
	(clean)
		# Interactively remove intermediate files left around by youtube-dl errors.
		set -x
		rm -i *.'jpg'        || true
		rm -i *.'m4a.part'   || true
		rm -i *.'mp4.part'   || true
		rm -i *.'temp.mp3'   || true
		rm -i *.'webm.part'  || true
		rm -i *.'webp'       || true
		;;
	(mp3)
		shift
		yd \
			--audio-format mp3 \
			--audio-quality 0 \
			--extract-audio \
			--format bestaudio \
			--no-playlist \
			"$@"
		;;
	(mp3p)
		shift
		yd \
			--audio-format mp3 \
			--audio-quality 0 \
			--extract-audio \
			--format bestaudio \
			--yes-playlist \
			"$@"
		;;
	(vid)
		shift
		yd \
			--format best \
			--no-playlist \
			"$@"
		;;
	(vidp)
		shift
		yd \
			--format best \
			--yes-playlist \
			"$@"
		;;
	(*)
		exit 1
		;;
esac
