#!/bin/sh -e
#
# - extract youtube links from youtube-dl filenames

y='https://www.youtube.com/watch?v='
test "${YDR_EMBED:-0}" -ne '0' && y='https://www.youtube.com/embed/'

for f in "$@"
do
	printf %s\\n "$f" |
		sed -E "s|^(.+)-(.{11})\..+$|${y}\2 \1|"
done
