#!/bin/sh -eu
#
# - print all playlists from a youtube channel

channel="${1}"; shift
case "$channel" in
	(*'/playlists')  playlists="$channel"              ;;
	(*)              playlists="${channel}/playlists"  ;;
esac

yt-dlp --dump-json --flat-playlist "${playlists}" |
	jq -r ".webpage_url"
