#!/bin/sh -eu
#
# - download subs for a youtube video
#
# TODO: can you know what the original language is?

yt-dlp \
	-- "$1"
	--no-embed-thumbnail \
	--skip-download \
	--sub-lang="${lang}" \
	--write-auto-sub \
	# --output "%(id)s"
	# --convert-subs=lrc \
